const POST_STATUS_PUBLISH = "publish"
const POST_TYPE_DRAFT = "draft"
const POST_TYPE_INHERIT = "inherit"

export const POST_STATUS_CONSTANTS = {
    POST_STATUS_PUBLISH,
    POST_TYPE_DRAFT,
    POST_TYPE_INHERIT
}