const SIYUAN_PAGE_ATTR_CUSTOM_SLUG_KEY = "custom-slug"
const SIYUAN_PAGE_ATTR_CUSTOM_DESC_KEY = "custom-desc"

export const SIYUAN_PAGE_ATTR_KEY = {
    SIYUAN_PAGE_ATTR_CUSTOM_SLUG_KEY,
    SIYUAN_PAGE_ATTR_CUSTOM_DESC_KEY
}