// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core"

export {}

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElAlert: typeof import("element-plus/es")["ElAlert"]
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElDialog: typeof import("element-plus/es")["ElDialog"]
    ElFooter: typeof import("element-plus/es")["ElFooter"]
    ElForm: typeof import("element-plus/es")["ElForm"]
    ElFormItem: typeof import("element-plus/es")["ElFormItem"]
    ElHeader: typeof import("element-plus/es")["ElHeader"]
    ElInput: typeof import("element-plus/es")["ElInput"]
  }
}
