/*
 * Copyright (c) 2023, Terwer . All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Terwer designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Terwer in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Terwer, Shenzhen, Guangdong, China, youweics@163.com
 * or visit www.terwer.space if you need additional information or have any
 * questions.
 */

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {}

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElAlert: typeof import("element-plus/es")["ElAlert"]
    ElAutocomplete: typeof import("element-plus/es")["ElAutocomplete"]
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElButtonGroup: typeof import("element-plus/es")["ElButtonGroup"]
    ElCard: typeof import("element-plus/es")["ElCard"]
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"]
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"]
    ElCol: typeof import("element-plus/es")["ElCol"]
    ElContainer: typeof import("element-plus/es")["ElContainer"]
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"]
    ElDialog: typeof import("element-plus/es")["ElDialog"]
    ElForm: typeof import("element-plus/es")["ElForm"]
    ElFormItem: typeof import("element-plus/es")["ElFormItem"]
    ElHeader: typeof import("element-plus/es")["ElHeader"]
    ElIcon: typeof import("element-plus/es")["ElIcon"]
    ElInput: typeof import("element-plus/es")["ElInput"]
    ElMain: typeof import("element-plus/es")["ElMain"]
    ElOption: typeof import("element-plus/es")["ElOption"]
    ElPageHeader: typeof import("element-plus/es")["ElPageHeader"]
    ElPagination: typeof import("element-plus/es")["ElPagination"]
    ElPopover: typeof import("element-plus/es")["ElPopover"]
    ElRadio: typeof import("element-plus/es")["ElRadio"]
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"]
    ElRow: typeof import("element-plus/es")["ElRow"]
    ElSelect: typeof import("element-plus/es")["ElSelect"]
    ElSkeleton: typeof import("element-plus/es")["ElSkeleton"]
    ElSwitch: typeof import("element-plus/es")["ElSwitch"]
    ElTable: typeof import("element-plus/es")["ElTable"]
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"]
    ElTabPane: typeof import("element-plus/es")["ElTabPane"]
    ElTabs: typeof import("element-plus/es")["ElTabs"]
    ElTag: typeof import("element-plus/es")["ElTag"]
    ElTooltip: typeof import("element-plus/es")["ElTooltip"]
    ElTreeSelect: typeof import("element-plus/es")["ElTreeSelect"]
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"]
  }
}
