POST http://localhost:9564/kms16_release/api/kms-multidoc/kmsMultidocKnowledgeRestService/addDoc
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic {{kmsUsername}} {{kmsPassword}}

--WebAppBoundary
Content-Disposition: form-data; name="fdDocTemplateId"
Content-Type: text/plain

181f20dcfc5744e90b0b8254499b4af0
--WebAppBoundary
Content-Disposition: form-data; name="docSubject"
Content-Type: text/plain

测试文档标题
--WebAppBoundary
Content-Disposition: form-data; name="docContent"
Content-Type: text/plain

测试文档内容
--WebAppBoundary
Content-Disposition: form-data; name="fdDocCreator"
Content-Type: text/plain

180f58069509ef61dd964994e4591dab
--WebAppBoundary
Content-Disposition: form-data; name="authorType"
Content-Type: text/plain

1
--WebAppBoundary
Content-Disposition: form-data; name="docAuthor"
Content-Type: text/plain

180f58069509ef61dd964994e4591dab
--WebAppBoundary--

#{
#  "code": "200",
#  "success": "success",
#  "data": {
#    "docContent": "测试文档内容",
#    "docCreateTime": "2022-08-20 17:15",
#    "fdId": "182ba88e8d8f4e3ad36314943b189939",
#    "docSubject": "测试文档标题",
#    "docCreatorId": "180f58069509ef61dd964994e4591dab"
#  },
#  "msg": "操作成功！"
#}