/*
 * Copyright (c) 2022-2023, Terwer . All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Terwer designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Terwer in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Terwer, Shenzhen, Guangdong, China, youweics@163.com
 * or visit www.terwer.space if you need additional information or have any
 * questions.
 */

import { describe, expect } from "vitest"
import { cutWords, isEmptyString, jiebaToHotWords, pinyinSlugify, zhSlugify } from "~/utils/util"
import { LogFactory } from "~/utils/logUtil"

describe("util test", () => {
  const logger = LogFactory.getLogger()

  it("zhSlugify test", async () => {
    const result = await zhSlugify("我爱中国")
    logger.info("zhSlugify result=>", result)
    expect(result).contains("china")
  })

  it("pinyinSlugify test", async () => {
    const result = pinyinSlugify("我爱中国")
    logger.info("pinyinSlugify result=>", result)
    expect(result).contains("wo")
  })

  it("cutWords test", async () => {
    const words = "今天天气很好"
    const result = await cutWords(words)
    logger.info("cutWords result=>", result)
  })

  it("jiebaToHotWords test", () => {
    const words = [
      "文档",
      "协同",
      "开发",
      "2022/05/25",
      "需求",
      "评审",
      "1",
      "、",
      "后台",
      "配置",
      "，",
      "可",
      "选择",
      "wps",
      "或者",
      "石墨",
      "文档",
      "2022/05/31ui",
      "评审",
      "2022/06/10",
      "开发",
      "遇到",
      "的",
      "问题",
      "1",
      "、",
      "未",
      "开启",
      "文档",
      "中台",
      "时候",
      "的",
      "提示",
      "，",
      "以及",
      "其他",
      "页面",
      "的",
      "缺省",
      "样式",
      "。",
      "2022/6/24",
      "遗留问题",
      "1",
      "、",
      "分享",
      "发送",
      "待办",
      "-",
      "已",
      "完成",
      "2",
      "、",
      "团队",
      "文档",
      "发送",
      "待办",
      "-",
      "已",
      "完成",
      "3",
      "、",
      "权限",
      "-",
      "已",
      "完成",
      "4",
      "、",
      "团队",
      "文档",
      "传",
      "fdteamid",
      "，",
      "后台",
      "做",
      "权限",
      "判断",
      "，",
      "如果",
      "不是",
      "这个",
      "团队",
      "的人",
      "，",
      "提示",
      "无",
      "权限",
      "页面",
      "-",
      "已",
      "完成",
      "5",
      "、",
      "看看",
      "能",
      "不能",
      "隐藏",
      "默认",
      "标题",
      "-todo6",
      "、",
      "excel",
      "和",
      "ppt",
      "的",
      "知识",
      "助手",
      "不",
      "做",
      "-",
      "已",
      "完成",
      "2022/7/8",
      "遗留问题",
      "1",
      "、",
      "文档",
      "和",
      "模板",
      "的",
      "拷贝",
      "、",
      "打印",
      "2",
      "、",
      "收藏夹",
      "重复",
      "收藏",
      "2022/7/19",
      "遗留问题",
      "1",
      "、",
      "文档",
      "知识",
      "助手",
      "太长加",
      "滚动条",
      "2",
      "、",
      "附件",
      "的",
      "显示",
      "与",
      "预览",
      "3",
      "、",
      "收起",
      "4",
      "、",
      "自定义",
      "confirm",
      "弹窗",
      "5",
      "、",
      "缺省",
      "页面",
      "2022/7/19",
      "待转",
      "单",
      "问题",
      "1",
      "、",
      "搜索",
      "关键字",
      "去掉",
      "2",
      "、",
      "未",
      "选中",
      "的",
      "时候",
      "按钮",
      "变成",
      "全部",
      "3",
      "、",
      "右侧",
      "滚动条",
      "、",
      "分页",
      "4",
      "、",
      "带",
      "表格",
      "收藏",
      "2022/7/20",
      "待",
      "解决问题",
      "1",
      "、",
      "excel",
      "、",
      "ppt",
      "格式",
      "时",
      "，",
      "点",
      "不",
      "开",
      "右侧",
      "工具栏",
      "图标",
      "2",
      "、",
      "段落",
      "收藏",
      "不能",
      "用",
      "3",
      "、",
      "详情",
      "页面",
      "调整",
      "4",
      "、",
      "筛选",
      "项",
      "修复",
      "5",
      "、",
      "git",
      "无法访问",
      "1",
      "、",
      "摘要",
      "、",
      "正文",
      "（",
      "正文",
      "图片",
      "）",
      "、",
      "附件",
      "2",
      "、",
      "搜索",
      "结果",
      "，",
      "状态",
      "30",
      "，",
      "有",
      "可",
      "阅读",
      "权限",
      "（",
      "确认",
      "）",
      "3",
      "、",
      "链接",
      "只",
      "展示",
      "图标",
      "放在",
      "标题",
      "右侧",
      "1",
      "、",
      "插入",
      "图片",
      "、",
      "表格",
      "2",
      "、",
      "维基",
      "目录",
      "3",
      "、",
      "搜索",
      "结果",
      "只",
      "显示",
      "文档",
      "不",
      "显示",
      "附件",
      "4",
      "、",
      "知识",
      "助手",
      "切换",
      "tab",
      "触发",
      "数据",
      "更新",
    ]
    // const result = jiebaToHotWords(words,3)
    const result = jiebaToHotWords(words)
    logger.info("jiebaToHotWords result=>", result)
  })

  it("isEmptyString test", () => {
    // const str = undefined
    const str = "undefined"
    logger.info(typeof str)
    logger.info(str == "undefined")
    const result = isEmptyString(str)
    logger.info("isEmptyString result=>", result)
  })
})
